version: "3"
services:
  client:
    image: node:12.18.4
    working_dir: /code
    ports:
      - 8080:8080
    volumes:
      - type: bind
        source: ./client
        target: /code
    command: bash -c 'npm install && npm run start'
  server:
    image: node:12.18.4
    working_dir: /code
    ports:
      - 3000:3000
    environment:
      - PGUSER=anonymind
      - PGHOST=db
      - PGPASSWORD=password
      - PGDATABASE=anonymind-db
      - PGPORT=5432
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./server
        target: /code
    command: bash -c "npm install && npm start"

  db:
    image: postgres:latest
    volumes:
      - "dbdata:/var/lib/postgresql/data"
      - "./db:/docker-entrypoint-initdb.d/:ro"
    environment:
      - POSTGRES_DB=anonymind-db
      - POSTGRES_USER=anonymind
      - POSTGRES_PASSWORD=password
volumes:
  dbdata:
